update readme
runtimerevolution/revent-api pull request #67
Opened 2023-09-14 17:23 UTC by claudio-vagarinho

2023-09-18 09:56 UTC, kenvontucky commented on README.md
Let's add something like

## TL;DR

Check what's available in the [Makefile](./Makefile).

Python 3.10.X environment must exist and be active

```bash
make up
make migrate
make run
```

2023-09-19 10:29 UTC, tiagocardoso98 approved these changes

2023-09-19 14:19 UTC, kenvontucky requested changes

2023-09-19 14:19 UTC, kenvontucky commented on Makefile
> +	poetry run python manage.py runserver
this should be applied to the migrations, migrate and test entries in Makefile

2023-09-20 08:05 UTC, kenvontucky approved these changes

2023-09-20 08:31 UTC, merged