Create GitHub actions configuration for testing
runtimerevolution/revent-api pull request #68
Opened 2023-09-15 08:51 UTC by claudio-vagarinho

Created django.yml for github actions to run tests whenever we create a PR.
psycog package needed to be updated in order for the test to run

2023-09-15 15:08 UTC, claudio-vagarinho commented
update psycog in order to be able to run the tests

2023-09-19 10:28 UTC, tiagocardoso98 approved these changes

2023-09-19 14:19 UTC, kenvontucky approved these changes

2023-09-19 14:20 UTC, kenvontucky requested changes
Please update env.sample with the new variables

2023-09-20 08:06 UTC, kenvontucky approved these changes

2023-09-20 08:35 UTC, merged